<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>VHDL-2019 Syntax Bundle by Brian Padalino (ocnqnyvab@tznvy.pbz)</string>
	<key>fileTypes</key>
	<array>
		<string>vhd</string>
		<string>vhdl</string>
		<string>vho</string>
	</array>
	<key>name</key>
	<string>VHDL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#syntax_highlighting</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>--</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-dash.vhdl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block.vhdl</string>
				</dict>
			</array>
		</dict>
		<key>constants_numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([+\-]?[\d_]+\.[\d_]+([eE][+\-]?[\d_]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.floating_point.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b16#[0-9A-Fa-f_]+#</string>
					<key>name</key>
					<string>constant.numeric.integer.base_16_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b15#[0-9A-Ea-e_]+#</string>
					<key>name</key>
					<string>constant.numeric.integer.base_15_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b14#[0-9A-Da-d_]+#</string>
					<key>name</key>
					<string>constant.numeric.integer.base_14_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b13#[0-9A-Ca-c_]+#</string>
					<key>name</key>
					<string>constant.numeric.integer.base_13_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b12#[0-9A-Ba-b_]+#</string>
					<key>name</key>
					<string>constant.numeric.integer.base_12_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b11#[0-9Aa_]+#</string>
					<key>name</key>
					<string>constant.numeric.integer.base_11_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b10#[0-9_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_10_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b9#[0-8_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_9_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b8#[0-7_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_8_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b7#[0-6_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_7_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b6#[0-5_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_6_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b5#[0-4_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_5_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b4#[0-3_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_4_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b3#[0-2_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_3_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b2#[01_]+#</string>
					<key>name</key>
					<string>constant.numeric.base_2_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bad.number.vhdl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\d+)?#.*?#)</string>
					<key>name</key>
					<string>constant.numeric.base_pound_number_pound.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[\d_]+([eE][\d_]+)?\b</string>
					<key>name</key>
					<string>constant.numeric.integer.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d+)?[sSuU]?[xX]"[0-9a-fA-F_uUxXzZwWlLhH\-]+"</string>
					<key>name</key>
					<string>constant.numeric.quoted.double.string.hex.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d+)?[sSuU]?[dD]"[0-9uUxXzZwWlLhH\-]+"</string>
					<key>name</key>
					<string>constant.numeric.quoted.double.string.decimal.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d+)?[sSuU]?[oO]"[0-7_uUxXzZwWlLhH\-]+"</string>
					<key>name</key>
					<string>constant.numeric.quoted.double.string.octal.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d+)?[sSuU]?[bB]?"[01_uUxXzZwWlLhH\-]+"</string>
					<key>name</key>
					<string>constant.numeric.quoted.double.string.binary.vhdl</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.quoted.double.string.vhdl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([bBdDoOsSuUxX]".+?")</string>
					<key>name</key>
					<string>constant.numeric.quoted.double.string.illegal.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'[01uUxXzZwWlLhH\-]'</string>
					<key>name</key>
					<string>constant.numeric.quoted.single.std_logic</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>'(?i:active|ascending|base|converse|delayed|designated_subtype|driving|element|event|high|image|index|instance|instance_name|last|left|leftof|length|low|mirror|path|path_name|pos|pred|quiet|range|record|reverse|reverse_range|right|rightof|simple|stable|succ|transaction|val|value)\b</string>
					<key>name</key>
					<string>keyword.control.attributes.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|component|configuration|constant|context|default|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|private|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|view|wait|when|while|with|xnor|xor)\b</string>
					<key>name</key>
					<string>keyword.control.language.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:case)(\?|\b)</string>
					<key>name</key>
					<string>keyword.control.language.case.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\+|\-|(\?)?&lt;=|(\?)?=|(\?)?/=|=&gt;|:=|(\?)?&gt;=|&lt;&gt;|(\?)?&gt;|(\?)?&lt;|/|\||&amp;|(\*{1,2})|\?\?)</string>
					<key>name</key>
					<string>keyword.operator.vhdl</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.vhdl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.vhdl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(').(')</string>
					<key>name</key>
					<string>string.quoted.single.vhdl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.vhdl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.vhdl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.vhdl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.vhdl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\\</string>
					<key>end</key>
					<string>\\</string>
					<key>name</key>
					<string>string.other.backslash.vhdl</string>
				</dict>
			</array>
		</dict>
		<key>support_constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:math_1_over_e|math_1_over_pi|math_1_over_sqrt_2|math_2_pi|math_3_pi_over_2|math_deg_to_rad|math_e|math_log10_of_e|math_log2_of_e|math_log_of_10|math_log_of_2|math_pi|math_pi_over_2|math_pi_over_3|math_pi_over_4|math_rad_to_deg|math_sqrt_2|math_sqrt_pi)\b</string>
					<key>name</key>
					<string>support.constant.ieee.math_real.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:math_cbase_1|math_cbase_j|math_czero|positive_real|principal_value)\b</string>
					<key>name</key>
					<string>support.constant.ieee.math_complex.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:true|false)\b</string>
					<key>name</key>
					<string>support.constant.std.standard.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:ascending|descending)\b</string>
					<key>name</key>
					<string>support.constant.std.direction.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:state_(closed|open))\b</string>
					<key>name</key>
					<string>support.constant.textio.state.file.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(read|write|read_write)_mode)\b</string>
					<key>name</key>
					<string>support.constant.textio.mode.file.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:dir_separator|file_(name|path|line))\b</string>
					<key>name</key>
					<string>support.constant.std.env.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(tool_(edition|name|type|vendor|version))|(vhdl_version))</string>
					<key>name</key>
					<string>support.constant.std.directives.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:class_(enumeration|physical|integer|floating|record|array|access|file|protected))\b</string>
					<key>name</key>
					<string>support.constant.std.reflection.vhdl</string>
				</dict>
			</array>
		</dict>
		<key>support_functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:getenv|finish|stop|resolution_limit)\b</string>
					<key>name</key>
					<string>support.function.std.env.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:readline|read|writeline|write|endfile|endline)\b</string>
					<key>name</key>
					<string>support.function.std.textio.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:rising_edge|falling_edge|to_bit|to_bitvector|to_stdulogic|to_stdlogicvector|to_stdulogicvector|is_x)\b</string>
					<key>name</key>
					<string>support.function.ieee.std_logic_1164.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:shift_left|shift_right|rotate_left|rotate_right|resize|to_integer|to_unsigned|to_signed)\b</string>
					<key>name</key>
					<string>support.function.ieee.numeric_std.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:arccos(h?)|arcsin(h?)|arctan|arctanh|cbrt|ceil|cos|cosh|exp|floor|log10|log2|log|realmax|realmin|round|sign|sin|sinh|sqrt|tan|tanh|trunc)\b</string>
					<key>name</key>
					<string>support.function.ieee.math_real.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:arg|cmplx|complex_to_polar|conj|get_principal_value|polar_to_complex)\b</string>
					<key>name</key>
					<string>support.function.ieee.math_complex.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:file_(canseek|close|mode|open|position|rewind|seek|size|state|truncate))\b</string>
					<key>name</key>
					<string>support.function.textio.file.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:deallocate|get_call_path)\b</string>
					<key>name</key>
					<string>support.function.std.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(local|gm)time)\b</string>
					<key>name</key>
					<string>support.function.std.time.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:get_subtype_mirror|to_value_mirror|pos|image|to_subtype_mirror|enumeration_literal|simple_name|left|right|low|high|length|ascending|value|unit_index|units_length|unit_name|unit_index|scale|element_(index|name|subtype)|get_value_class|is_null|to_subtype_mirror|designated_subtype|get_file_logical_name|get_file_open_kind|to_(enumeration|integer|floating|physical|record|array|access|file|protected)|get)\b</string>
					<key>name</key>
					<string>support.function.std.reflection.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(ClearVhdlAssert|IsVhdlAssertFailed|[GS]etVhdlAssertCount|[GS]etVhdlAssertEnable|[GS]etVhdlAssertFormat|[GS]etVhdlReadSeverity))\b</string>
					<key>name</key>
					<string>support.function.std.assert.vhdl</string>
				</dict>
			</array>
		</dict>
		<key>support_types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?i:boolean|bit|character|severity_level|integer(_vector)?|real(_vector)?|time|delay_length|now|natural|positive|string|bit_vector|file_open_kind|file_open_status|fs|ps|ns|us|ms|sec|min|hr|severity_level|note|warning|error|failure)\b</string>
					<key>name</key>
					<string>support.type.std.standard.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:line|text|side|width|input|output)\b</string>
					<key>name</key>
					<string>support.type.std.textio.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:std_(u)?logic(_vector)?)\b</string>
					<key>name</key>
					<string>support.type.ieee.std_logic_1164.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:signed|unsigned)\b</string>
					<key>name</key>
					<string>support.type.ieee.numeric_std.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:complex|complex_polar)\b</string>
					<key>name</key>
					<string>support.type.ieee.math_complex.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:sfixed|ufixed)\b</string>
					<key>name</key>
					<string>support.type.ieee.fixed.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:float(32|64|128)?)\b</string>
					<key>name</key>
					<string>support.type.float.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:time_record)\b</string>
					<key>name</key>
					<string>support.type.std.time.vhdl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(access_|array_|enumeration_|file_|floating_|integer_|physical_|protected_|record_)?(subtype|value)_mirror(_pt)?|(natural_|positive_)?index|value_class)\b</string>
					<key>name</key>
					<string>support.type.std.reflection.vhdl</string>
				</dict>
			</array>
		</dict>
		<key>syntax_highlighting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants_numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support_types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support_functions</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.vhdl</string>
	<key>uuid</key>
	<string>B582CBD9-DEFE-4CEC-96B7-11CABB74186D</string>
</dict>
</plist>
